name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy_job:
    # Skip the deploy-close dance on merged PRs
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') }}
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    # ⬇️ Build-time environment variables for Vite
    env:
      VITE_SUPABASE_URL:  ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Optional: speed up incremental builds & cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: '20'      # pick an LTS you use locally
          cache: 'npm'

      - run: npm ci               # install deps exactly
      - run: npm run build        # generates /dist with Vite

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FIELD_0CEDD170F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}      # PR comments, etc.
          action: "upload"
          app_location: "/"    # root of your repo
          api_location: ""     # empty because no Azure Functions yet
          output_location: "dist"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_FIELD_0CEDD170F }}
          action: "close"
